In [26]:
import pandas as pd
import numpy as np

data = pd.read_csv('checkins.dat', delimiter="|", header=0)

In [28]:
data.columns = data.columns.str.strip()
data.columns

Index([u'id', u'user_id', u'venue_id', u'latitude', u'longitude',
       u'created_at'],
      dtype='object')

In [35]:
data["latitude"] = data["latitude"].str.strip()
data["latitude"].replace('', np.nan, inplace=True)
data.dropna(inplace=True)

In [32]:
data.dropna(inplace=True)

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 396634 entries, 1 to 1021964
Data columns (total 6 columns):
id            396634 non-null int64
user_id       396634 non-null int64
venue_id      396634 non-null int64
latitude      396634 non-null object
longitude     396634 non-null object
created_at    396634 non-null object
dtypes: int64(3), object(3)
memory usage: 21.2+ MB


In [39]:
data.head()

id  user_id  venue_id    latitude            longitude  \
1   984222    15824      5222  38.8951118         -77.0363658    
3   984234    44652      5222   33.800745           -84.41052    
7   984291   105054      5222  45.5234515        -122.6762071    
9   984318  2146539      5222   40.764462         -111.904565    
10  984232    93870    380645  33.4483771        -112.0740373    

              created_at  
1    2012-04-21 17:43:47  
3    2012-04-21 17:43:43  
7    2012-04-21 17:39:22  
9    2012-04-21 17:35:46  
10   2012-04-21 17:38:18

In [40]:
from sklearn.cluster import MeanShift, estimate_bandwidth

In [48]:
data_t = data.head(100000)

In [52]:
coords = data_t[["latitude", "longitude"]]

In [54]:
coords.head()

latitude            longitude
1   38.8951118         -77.0363658 
3    33.800745           -84.41052 
7   45.5234515        -122.6762071 
9    40.764462         -111.904565 
10  33.4483771        -112.0740373

In [55]:
ms = MeanShift(bandwidth=0.1)
ms.fit(coords)

MeanShift(bandwidth=0.1, bin_seeding=False, cluster_all=True, min_bin_freq=1,
     n_jobs=1, seeds=None)

In [73]:
len(ms.cluster_centers_)

3229

In [75]:
coords = [ms.cluster_centers_[i] for i in range(0, len(ms.cluster_centers_)) if np.bincount(ms.labels_)[i] > 15]

In [79]:
coords[0:5]

[array([ 40.7177164 , -73.99183542]),
 array([  33.44943805, -112.00213969]),
 array([  33.44638027, -111.90188756]),
 array([ 41.87824378, -87.62984336]),
 array([  37.68868157, -122.40933037])]

In [65]:
len(ms.labels_)

100000

In [77]:
offices = [[33.751277, -118.188740],
            [25.867736, -80.324116],
            [51.503016, -0.075479],
            [52.378894, 4.885084],
            [39.366487, 117.036146],
            [-33.868457, 151.205134]]

In [78]:
offices

[[33.751277, -118.18874],
 [25.867736, -80.324116],
 [51.503016, -0.075479],
 [52.378894, 4.885084],
 [39.366487, 117.036146],
 [-33.868457, 151.205134]]

In [81]:
import scipy as sc
sc.spatial.distance.euclidean(offices[0], offices[1])

38.676607521343655

In [93]:
allmin = []
for coord in coords:
    min_dist = 1000.0
    for office in offices:
        dist = sc.spatial.distance.euclidean(office, coord)
        if dist < min_dist: min_dist = dist
    allmin.append({"lt": coord[0], "lg": coord[1], "dist": min_dist})

In [102]:
pd.DataFrame(allmin).sort_values(['dist'], ascending=[1])

dist          lg         lt
410   0.007835  151.204776 -33.860630
374   0.009353    4.892317  52.372964
402   0.022674  -80.318891  25.845672
58    0.050058   -0.125537  51.502991
51    0.070848 -118.148924  33.809878
29    0.134109  -80.217938  25.785812
166   0.167406  -80.283429  25.705350
92    0.188876  -80.199991  26.010098
87    0.195779 -118.048928  33.888325
42    0.211811 -118.362091  33.872986
285   0.222233 -118.168371  33.972575
315   0.271301  -80.334347  26.138844
119   0.294979 -118.007405  33.983936
55    0.302270  -80.158907  26.120863
27    0.304731 -117.891249  33.817306
11    0.314884 -118.248709  34.060398
32    0.338810 -117.858789  33.674303
158   0.340846  -80.250716  26.200585
17    0.378688 -118.438998  34.035487
47    0.386706 -118.118012  34.131460
64    0.398778 -117.980389  34.091298
24    0.409983 -118.351884  34.127402
35    0.410418 -118.223617  34.160210
50    0.448055 -117.752074  33.650896
100   0.493387 -117.816472  34.075079
144   0.540471  -80.085279  26.352571
90    0.574205 -118.549277  34.198182
75    0.603093 -117.671785  34.061886
223   0.619070 -117.647024  33.451624
284   0.638534 -117.563958  33.883084
..         ...         ...        ...
379  25.089676  121.015826  14.594446
421  25.105811  -96.787294  46.876820
409  25.327381  -94.685900  46.729553
474  26.641656   28.976960  41.005270
260  30.396671  100.615515  13.786798
208  30.498853  100.513362  13.731011
279  32.911701   37.623850  55.748350
468  36.153857   34.788657  32.059502
287  39.353789  101.675560   3.134276
367  40.216526   98.677329   3.584888
157  40.247365  103.820220   1.350837
327  40.276387  113.921327  -0.789275
171  41.574655 -157.856817  21.305571
395  41.692704 -158.003045  21.377810
418  41.952897 -149.900278  61.218056
358  43.940864  115.211340  -8.664363
536  46.673305  107.148452  -6.247447
33   46.704762  106.844660  -6.212767
502  46.725232  106.624447  -6.183966
251  46.765770  112.741673  -7.267715
210  46.811113  106.813152  -6.314698
155  47.230236  107.607743  -6.913102
433  47.625975  110.366640  -7.790179
355  57.254114   55.311667  25.264444
561  59.558186  -71.616452 -33.050462
105  59.806393  -46.638219 -23.549518
428  60.090305  -70.570740 -33.425741
261  61.287238  -43.209587 -22.903539
103  61.450391   36.522964  -0.301226
435  64.340495  -58.371865 -34.611996

[592 rows x 3 columns]